### ISSUE TITLE
S37 orbit-1 data file

### ISSUE THREAD

**Issue by hposborn** [SSDataLab/tess-cloud#1]
Hi Geert+co,

Just to make you aware that there is new S37 (orbit-1) TICA data on MAST (https://archive.stsci.edu/hlsp/tica) which we would love to access through `tess-cloud`.
Is there some way for users to generate the `tess-s0037-tica-ffi-catalog.parquet` file which acts as the index for the file locations, or does that need to be pushed to the repo on your end?

Thanks,
Hugh

**Comment by barentsen** [comment]
Thanks for the reminder.  I'll generate the sector 37 image catalog now and expect to push it to the repo in 15 mins.

Creating the catalog involves opening the header of every FFI file to grab some meta data and record the byte position of the first pixel, so that cutouts know which bytes to grab.

I'll add the catalog to the repo in a few minutes, but if you ever wanted to make it yourself, the syntax is:
```python
from tess_cloud.tica import save_tica_ffi_catalog
save_tica_ffi_catalog(sector=37)
```

**Comment by barentsen** [comment]
I added `tess-cloud/src/tess_cloud/data/tess-s0037-tica-ffi-catalog.parquet` to the repo.

I did not push a new package to pypi, but cloning this repo and installing it using `pip install .` should sort you out!
